---
- name: Enable RabbitMQ Prometheus plugin
  hosts: rabbitmq
  become: true
  gather_facts: false

  tasks:
    - name: Enable RabbitMQ Prometheus plugin
      ansible.builtin.command:
        cmd: rabbitmq-plugins enable rabbitmq_prometheus
      register: rabbitmq_prometheus_enable
      changed_when: "'configured' in rabbitmq_prometheus_enable.stdout"

    - name: Wait for RabbitMQ Prometheus port
      ansible.builtin.wait_for:
        port: 15692
        host: "0.0.0.0"
        timeout: 30
